# Generated by Django 2.0.9 on 2018-11-06 00:11

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('razaPredominante', models.CharField(max_length=50, verbose_name='Raza Predominante')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('estado', models.CharField(choices=[('1', 'Adoptado'), ('2', 'Disponible'), ('3', 'Rescatado')], max_length=50, verbose_name='Estado')),
                ('imagen', cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagen')),
            ],
        ),
        migrations.CreateModel(
            name='UsuariosAdoptantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('correo', models.CharField(max_length=50, verbose_name='Correo')),
                ('clave', models.CharField(max_length=50, verbose_name='Clave')),
            ],
        ),
    ]
