# Generated by Django 2.0.9 on 2018-11-06 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsuariosAdoptantes',
            new_name='Adoptante',
        ),
        migrations.RenameModel(
            old_name='Perros',
            new_name='Perro',
        ),
    ]
