# Generated by Django 2.0.9 on 2018-11-07 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0002_auto_20181105_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Adoptante',
        ),
        migrations.RemoveField(
            model_name='perro',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='perro',
            name='razaPredominante',
        ),
        migrations.AddField(
            model_name='perro',
            name='dueno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='perro',
            name='foto',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='perro',
            name='raza',
            field=models.CharField(default='Quiltro', max_length=100),
        ),
        migrations.AlterField(
            model_name='perro',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='perro',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.Estado'),
        ),
        migrations.AlterField(
            model_name='perro',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
