# Generated by Django 2.0.9 on 2018-11-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20181107_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='estado',
            field=models.CharField(choices=[('1', 'Adoptado'), ('2', 'Disponible'), ('3', 'Rescatado')], max_length=50, verbose_name='Estado'),
        ),
    ]
