# Generated by Django 2.0.9 on 2018-11-11 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20181107_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perro',
            name='dueno',
        ),
        migrations.AlterField(
            model_name='perro',
            name='foto',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
